'use server'

import nodemailer from 'nodemailer'
import { NextResponse } from 'next/server'

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
})

export async function POST(req: Request) {
  try {
    const data = await req.json()
    const { name, email, subject, message } = data

    if (!name || !email || !message) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    function escapeHtml(str = '') {
      return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;')
    }

    function sanitizeHtml(html = '') {
      let s = String(html)
      // remove script/style blocks
      s = s.replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi, '')
      s = s.replace(/<style[\s\S]*?>[\s\S]*?<\/style>/gi, '')
      // strip event handlers like onclick=
      s = s.replace(/\son\w+=(\"|\')(.*?)(\"|\')/gi, '')
      // neutralize javascript: hrefs
      s = s.replace(/href=(\"|\')javascript:[^\"']*(\"|\')/gi, 'href="#"')
      return s
    }

    const safeName = escapeHtml(name)
    const safeEmail = escapeHtml(email)
    const safeSubject = escapeHtml(subject || `New contact from ${name}`)
    const safeMessageHtml = sanitizeHtml(message)
    const safeMessageText = String(message).replace(/<[^>]+>/g, '')
    const timestamp = new Date().toLocaleString()

    const htmlBody = `<!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <title>New contact</title>
      </head>
      <body style="font-family:Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; background:#f6f8fb; margin:0; padding:24px;">
        <div style="max-width:680px; margin:0 auto;">
          <div style="background:linear-gradient(90deg,#eef2ff,#fff0f6); padding:18px 22px; border-radius:12px; box-shadow:0 6px 18px rgba(12,20,40,0.06);">
            <h2 style="margin:0; color:#0f172a; font-size:20px">New message from your site</h2>
            <p style="margin:6px 0 0; color:#475569; font-size:13px">Received: ${timestamp}</p>
          </div>

          <div style="background:#ffffff; padding:20px; border-radius:12px; margin-top:16px; border:1px solid #eef2ff;">
            <div style="margin-bottom:12px;">
              <span style="color:#64748b; font-size:13px;">Plan:</span>
              <span style="margin-left:8px; font-weight:700; color:#0f172a">${safeSubject}</span>
            </div>

            <table role="presentation" style="width:100%; border-collapse:collapse; margin-bottom:14px;">
              <tr>
                <td style="width:110px; color:#64748b; font-size:13px; vertical-align:top; padding:4px 0">Name</td>
                <td style="padding:4px 0; color:#0f172a; font-weight:600">${safeName}</td>
              </tr>
              <tr>
                <td style="color:#64748b; font-size:13px; padding:4px 0">Email</td>
                <td style="padding:4px 0; color:#0f172a">${safeEmail}</td>
              </tr>
            </table>

            <div style="margin-bottom:8px; color:#64748b; font-size:13px;">message:</div>

            <div style="background:#f8fafc; padding:14px; border-radius:8px; color:#0f172a; line-height:1.5; font-size:14px;">
              ${safeMessageHtml}
            </div>

            <p style="margin:14px 0 0; color:#94a3b8; font-size:12px">Reply to: <a href="mailto:${safeEmail}" style="color:#2563eb; text-decoration:none">${safeEmail}</a></p>
          </div>

          <p style="text-align:center; margin:18px 0 0; color:#94a3b8; font-size:12px">Generated by your website</p>
        </div>
      </body>
    </html>`

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: process.env.EMAIL_USER,
      replyTo: email,
      subject: safeSubject,
      text: `Name: ${name}\nEmail: ${email}\n\nPlan: ${safeSubject}\n\nmessage:\n${safeMessageText}`,
      html: htmlBody,
    }

    await transporter.sendMail(mailOptions)

    return NextResponse.json({ ok: true })
  } catch (err: any) {
    console.error('Mail error:', err)
    return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
  }
}
